# Generated by Django 2.2.24 on 2021-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
