# Generated by Django 2.2.24 on 2021-07-26 14:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bitbox', '0002_auto_20210726_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
